# Password generated by Terraform, never hardcoded — it lands in
# Terraform state (state itself is access-controlled and never in git,
# see envs/dev's backend config) and is separately written out via the
# password output for envs/dev to push into Key Vault, matching the
# manual setup's pattern exactly.
resource "random_password" "postgres_admin" {
  length  = 24
  special = false # avoids the URL-unsafe-character bug from the manual
  # deployment (ADR 0008) at the source, rather than remembering to
  # URL-encode a generated password later.
}

# A dedicated private DNS zone per environment, matching what the manual
# deployment ended up with (ADR 0008) — Postgres Flexible Server with
# private access needs one, and it must be linked to the same VNet the
# delegated subnet lives in.
resource "azurerm_private_dns_zone" "postgres" {
  name                = "${var.name}.private.postgres.database.azure.com"
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

resource "azurerm_private_dns_zone_virtual_network_link" "postgres" {
  name                  = "${var.name}-vnet-link"
  resource_group_name   = var.resource_group_name
  private_dns_zone_name = azurerm_private_dns_zone.postgres.name
  virtual_network_id    = var.vnet_id
  tags                  = var.tags
}

resource "azurerm_postgresql_flexible_server" "this" {
  name                = var.name
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags

  version  = "16"
  sku_name = "B_Standard_B1ms" # Burstable, matches the manual deployment
  # and the plan's D3.1 free-grant target (750 hrs/month).

  storage_mb        = 32768 # 32 GiB
  storage_tier      = "P4"
  auto_grow_enabled = false

  backup_retention_days        = 7
  geo_redundant_backup_enabled = false

  administrator_login    = "tadadmin"
  administrator_password = random_password.postgres_admin.result

  delegated_subnet_id = var.delegated_subnet_id
  private_dns_zone_id = azurerm_private_dns_zone.postgres.id

  # Explicit, not left to the provider default — private access
  # (delegated subnet + private DNS zone) is the whole point per D3.4 and
  # ADR 0008. The provider's schema defaults this to true, which the
  # plan output shows before Azure's own validation reconciles it against
  # delegated_subnet_id, but this is exactly the kind of thing not worth
  # leaving implicit given last session's networking saga.
  public_network_access_enabled = false

  # Depends on the zone link explicitly — Azure requires the DNS zone to
  # already be linked to the VNet before a Flexible Server can be
  # created with private access, and Terraform can't infer that
  # ordering purely from the private_dns_zone_id reference above.
  depends_on = [azurerm_private_dns_zone_virtual_network_link.postgres]
}

resource "azurerm_postgresql_flexible_server_database" "tad" {
  name      = var.database_name
  server_id = azurerm_postgresql_flexible_server.this.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}

# trivy flags AZU-0019/0021/0024 (log_connections, connection_throttling,
# log_checkpoints not explicitly configured). No azurerm_postgresql_
# flexible_server_configuration resources here for any of them:
# checked the real server's actual parameter defaults via
# `az postgres flexible-server parameter list` — log_connections,
# log_disconnections, and log_checkpoints all already default to "on" on
# PostgreSQL 16 Flexible Server, so a resource setting them to "on"
# would be a no-op that exists purely to satisfy a scanner. And
# connection_throttling isn't a real parameter on this resource/version
# at all (confirmed via a real ParameterNotExists apply error) — trivy's
# check also only recognizes the deprecated azurerm_postgresql_server
# resource type, never azurerm_postgresql_flexible_server (confirmed by
# reading the cached policy source). See .trivyignore for AZU-0021.
