# Password generated by Terraform, never hardcoded — it lands in
# Terraform state (state itself is access-controlled and never in git,
# see envs/dev's backend config) and is separately written out via the
# password output for envs/dev to push into Key Vault, matching the
# manual setup's pattern exactly.
resource "random_password" "postgres_admin" {
  length  = 24
  special = false # avoids the URL-unsafe-character bug from the manual
  # deployment (ADR 0008) at the source, rather than remembering to
  # URL-encode a generated password later.
}

# A dedicated private DNS zone per environment, matching what the manual
# deployment ended up with (ADR 0008) — Postgres Flexible Server with
# private access needs one, and it must be linked to the same VNet the
# delegated subnet lives in.
resource "azurerm_private_dns_zone" "postgres" {
  name                = "${var.name}.private.postgres.database.azure.com"
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

resource "azurerm_private_dns_zone_virtual_network_link" "postgres" {
  name                  = "${var.name}-vnet-link"
  resource_group_name   = var.resource_group_name
  private_dns_zone_name = azurerm_private_dns_zone.postgres.name
  virtual_network_id    = var.vnet_id
  tags                  = var.tags
}

resource "azurerm_postgresql_flexible_server" "this" {
  name                = var.name
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags

  version  = "16"
  sku_name = "B_Standard_B1ms" # Burstable, matches the manual deployment
  # and the plan's D3.1 free-grant target (750 hrs/month).

  storage_mb        = 32768 # 32 GiB
  storage_tier      = "P4"
  auto_grow_enabled = false

  backup_retention_days        = 7
  geo_redundant_backup_enabled = false

  administrator_login    = "tadadmin"
  administrator_password = random_password.postgres_admin.result

  delegated_subnet_id = var.delegated_subnet_id
  private_dns_zone_id = azurerm_private_dns_zone.postgres.id

  # Explicit, not left to the provider default — private access
  # (delegated subnet + private DNS zone) is the whole point per D3.4 and
  # ADR 0008. The provider's schema defaults this to true, which the
  # plan output shows before Azure's own validation reconciles it against
  # delegated_subnet_id, but this is exactly the kind of thing not worth
  # leaving implicit given last session's networking saga.
  public_network_access_enabled = false

  # Depends on the zone link explicitly — Azure requires the DNS zone to
  # already be linked to the VNet before a Flexible Server can be
  # created with private access, and Terraform can't infer that
  # ordering purely from the private_dns_zone_id reference above.
  depends_on = [azurerm_private_dns_zone_virtual_network_link.postgres]
}

resource "azurerm_postgresql_flexible_server_database" "tad" {
  name      = var.database_name
  server_id = azurerm_postgresql_flexible_server.this.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}

# Audit-log parameters trivy flags as missing by default (AZU-0019,
# AZU-0021, AZU-0024) — genuinely worth having for real incident
# diagnosis, not just to pass the scan, and free (log volume on a dev
# database is tiny).
resource "azurerm_postgresql_flexible_server_configuration" "log_connections" {
  name      = "log_connections"
  server_id = azurerm_postgresql_flexible_server.this.id
  value     = "on"
}

resource "azurerm_postgresql_flexible_server_configuration" "log_disconnections" {
  name      = "log_disconnections"
  server_id = azurerm_postgresql_flexible_server.this.id
  value     = "on"
}

resource "azurerm_postgresql_flexible_server_configuration" "log_checkpoints" {
  name      = "log_checkpoints"
  server_id = azurerm_postgresql_flexible_server.this.id
  value     = "on"
}

resource "azurerm_postgresql_flexible_server_configuration" "connection_throttling" {
  name      = "connection_throttling"
  server_id = azurerm_postgresql_flexible_server.this.id
  value     = "on"
}
