"""initial schema

Revision ID: 8fbb522232ae
Revises:
Create Date: 2026-09-27 16:38:07.680622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fbb522232ae"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_identity",
        sa.Column("test_id", sa.String(), nullable=False),
        sa.Column("flakiness_score", sa.Double(), nullable=True),
        sa.PrimaryKeyConstraint("test_id"),
    )
    op.create_table(
        "test_runs",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("suite_name", sa.String(), nullable=False),
        sa.Column("git_sha", sa.String(), nullable=False),
        sa.Column("branch", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=False),
        sa.Column("environment", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_test_runs_git_sha"), "test_runs", ["git_sha"], unique=False
    )
    op.create_table(
        "test_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("test_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("file", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Double(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("failure_message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("git_sha", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["test_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test_identity.test_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_results_git_sha"), "test_results", ["git_sha"], unique=False
    )
    op.create_index(
        "ix_test_results_test_id_started_at",
        "test_results",
        ["test_id", "started_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_test_results_test_id_started_at", table_name="test_results")
    op.drop_index(op.f("ix_test_results_git_sha"), table_name="test_results")
    op.drop_table("test_results")
    op.drop_index(op.f("ix_test_runs_git_sha"), table_name="test_runs")
    op.drop_table("test_runs")
    op.drop_table("test_identity")
    # ### end Alembic commands ###
