variable "location" {
  description = "Azure region for every resource. Sweden Central, not West Europe — see ADR 0007: this subscription's \"best available regions\" policy rejected West/North Europe for a first deployment."
  type        = string
  default     = "swedencentral"
}

variable "resource_suffix" {
  description = "Random suffix for globally-unique resource names, matching what already exists from the manual Phase 3 deployment (4471) so the ACR import in particular lines up with the real resource. Set explicitly, not generated by Terraform — a `random_id` resource would produce a *different* suffix than the manual resources already use, breaking the import."
  type        = string
  default     = "4471"
}

variable "postgres_suffix" {
  description = "Separate suffix for the Postgres server name only. Postgres server names are globally unique across all of Azure, and the manual deployment's pg-tad4471 (rg-tad-manual) still exists during the Phase 3 -> Phase 4 transition — reusing 4471 collides with it (ServerNameAlreadyExists). Every other resource type either gets imported (ACR, no collision) or hasn't been created with the shared suffix yet."
  type        = string
  default     = "dev4471"
}
