variable "location" {
  description = "Azure region for every resource. Sweden Central, not West Europe — see ADR 0007: this subscription's \"best available regions\" policy rejected West/North Europe for a first deployment."
  type        = string
  default     = "swedencentral"
}

variable "resource_suffix" {
  description = "Random suffix for globally-unique resource names, matching what already exists from the manual Phase 3 deployment (4471) so the ACR import in particular lines up with the real resource. Set explicitly, not generated by Terraform — a `random_id` resource would produce a *different* suffix than the manual resources already use, breaking the import."
  type        = string
  default     = "4471"
}
